title: Data Room example
author: MN

description: > # this means to ignore newlines until "baseurl:"
  MN testing creating a fleshed out website

# social links

show_excerpts: true # set to false to remove excerpts on the homepage
